"""new fields in Product table

Revision ID: 1eef445e06d9
Revises: 0afb3bc49f31
Create Date: 2024-02-17 14:22:13.123966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eef445e06d9'
down_revision: Union[str, None] = '0afb3bc49f31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('promotion', sa.String(), nullable=True))
    op.add_column('products', sa.Column('promocode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'promocode')
    op.drop_column('products', 'promotion')
    # ### end Alembic commands ###
